#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_RESERVATION_SIZE 256
#define STATE_ACCESS_DELAY_US 500000  // 500ms
#define MAX_JOB_FILE_NAME_SIZE 256
#define MAX_SESSION_COUNT 8
#define MAX_PIPE_NAME_SIZE 40
#define SETUP_REQUEST_BUFSIZ 82

enum OpCodes { OP_NONE, OP_SETUP, OP_QUIT, OP_CREATE, OP_RESERVE, OP_SHOW, OP_LIST };

#endif