#define MAX_RESERVATION_SIZE 256
#define STATE_ACCESS_DELAY_MS 10
#define BUFFER_FLUSH_THOLD 20
#define THREAD_ABORT_JOB_PROCESSING 0
#define THREAD_FOUND_BARRIER 1
#define JOBS_FILE_EXTENSION ".jobs"
